version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'

build_script:
  - ps: .\build.ps1
  - ps: .\run-sonar.ps1

artifacts:
  - path: 'artifacts\*.nupkg'

test_script:
  - ps: .\run-tests.ps1

deploy:
- provider: NuGet
  api_key:
    secure: DtVDH1ZfIR8E2oDLeSPxfn0WFXw3MCv4WhLkkQQl9LfEHswb5sdxdCYodNKhrKik
  artifact: /.*\.nupkg/
  on:
    branch: master
